---
title: "Tidying Data"
author: "Grace Lewin"
date: "8/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

Read in the wb_indicators.csv file, make sure to specify `na = c("..", "")`

```{r}
wb_indicators <- read_csv(here("data", "wb_indicators.csv"), na = c("..", ""))
```

## Reshape so that year is a single column

```{r}
wb_indicators_long <- wb_indicators %>% 
  pivot_longer(cols = '2001 [YR2001]':'2020 [YR2020]', 
               names_to = "year", 
               values_to = "indicator_value")
```

## Clean up that year column

```{r}
wb_data_sep <- wb_indicators_long %>% 
  separate(col = year, into = c("year", "year_chr", sep = " ")) %>% 
  select(-year_chr, -'Country Code', -'Series Code')
  
```


```{r}
df <- tribble(
  ~name, ~A, ~B, ~C,
  "teddy", 4, 5, 6,
  "khora", 9, 10, 11
)

df_long <- df %>% 
  pivot_longer(cols = A:C, 
               names_to = "dog_food",
               values_to = "ranking")
```

## Pivot wider to get all indicators in their own column

```{r}
wb_data_tidy <- wb_data_sep %>% 
  drop_na('Series Name') %>% 
  pivot_wider(names_from = 'Series Name', 
              values_from = indicator_value)

# drop_na() does case deletion. Wherever Series Name is na, the whole row is dropped

names(wb_data_tidy) <- c("country", "year", " ", "access_clean_fuels",
                         "access_electricity", "co2_emissions", "fossil_fuel_cons", 
                         "water_stress")

wb_data_tidy <- wb_data_tidy %>% 
  rename(country_name = country,
         electricity = access_electricity)
```


```{r}
df_wide <- df_long %>% 
  pivot_wider(names_from = dog_food, values_from = ranking)
```

